{% set name = "runtype" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/runtype-{{ version }}.tar.gz
  sha256: dd950a9077b37ef1b9e9c2287aac5d73f2d9a25a1cce62453445d7ff97ebec46

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - dataclasses
    - python >=3.6,<4.0

test:
  imports:
    - runtype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erezsh/runtype
  summary: Type dispatch and validation for run-time Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
