{% set name = "runtype" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/runtype-{{ version }}.tar.gz
  sha256: 496797110f7a94001fefadc181708b26262a0be5b456eb780300b6436b79d0fd

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0

test:
  imports:
    - runtype
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erezsh/runtype
  summary: Type dispatch and validation for run-time Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
