{% set name = "runtype" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/runtype-{{ version }}.tar.gz
  sha256: 2ef50cf46470e8939682ac7d82bc3e4a9137d270c83302762c1cc3fbe5020560

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - dataclasses
    - python >=3.6

test:
  imports:
    - runtype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erezsh/runtype
  summary: Type dispatch and validation for run-time Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
