{% set name = "runtype" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/runtype-{{ version }}.tar.gz
  sha256: c2d6905a56924f7147a573eb283c501297a0664fb1ecdbc728854929a432cd5e

build:
  noarch: python
  number: 0
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - dataclasses
    - python >=3.6

test:
  imports:
    - runtype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erezsh/runtype
  summary: Type dispatch and validation for run-time Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
